// Generated by scripts/sync-api-urls.sh - run after API Gateway changes
window.SITE_CONFIG = {
  TERMINAL_API_URL: 'https://4wmuu5rp71.execute-api.us-east-1.amazonaws.com/',
  BLACKJACK_API_URL: 'https://cdqyabz9mj.execute-api.us-east-1.amazonaws.com/prod/blackjack',
};
