#!/bin/bash
# Sync website/js/api-config.js from live AWS API Gateway endpoints.
set -euo pipefail

REGION="${AWS_REGION:-us-east-1}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/website/js/api-config.js"

terminal_endpoint="$(aws apigatewayv2 get-apis --region "$REGION" \
  --query "Items[?Name=='terminal-commands-api'].ApiEndpoint | [0]" --output text)"
blackjack_endpoint="$(aws apigatewayv2 get-apis --region "$REGION" \
  --query "Items[?Name=='blackjack-api'].ApiEndpoint | [0]" --output text)"

if [[ -z "$terminal_endpoint" || "$terminal_endpoint" == "None" ]]; then
  echo "Error: terminal-commands-api not found in $REGION" >&2
  exit 1
fi

if [[ -z "$blackjack_endpoint" || "$blackjack_endpoint" == "None" ]]; then
  echo "Error: blackjack-api not found in $REGION" >&2
  exit 1
fi

cat > "$OUT" <<EOF
// Generated by scripts/sync-api-urls.sh - run after API Gateway changes
window.SITE_CONFIG = {
  TERMINAL_API_URL: '${terminal_endpoint}/',
  BLACKJACK_API_URL: '${blackjack_endpoint}/prod/blackjack',
};
EOF

echo "Updated $OUT"
echo "  TERMINAL_API_URL=${terminal_endpoint}/"
echo "  BLACKJACK_API_URL=${blackjack_endpoint}/prod/blackjack"
